default: &default
  adapter: mysql2
  # adapter: postgresql
  # encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  # username: root
  # password: root
  # port: 3306
  timeout: 10000


development:
  <<: *default
  username: root
  password: root
  port: 8888
  database: building_rental

test:
  <<: *default
  username: root
  password: root
  database: building_rental

production:
  <<: *default
  port: 3306
  username: rootHarmoni2
  password: EW62iu7WPMt067cqcKHarmoni2
  database: building_rental
  # password: <%= ENV['BUILDING_RENTAL_DATABASE_PASSWORD'] %>
