default: &default
  # adapter: mysql2
  adapter: postgresql
  # encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  # username: root
  # password: root
  # port: 888
  timeout: 5000


development:
  <<: *default
  # username: postgres
  # password: 
  port: 5432
  database: building_rental

test:
  <<: *default
  database: building_rental

production:
  <<: *default
  database: building_rental
  # password: <%= ENV['BUILDING_RENTAL_DATABASE_PASSWORD'] %>
